repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.8"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: "23.12.0"
    hooks:
      - id: black
